/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./index.tsx",
    "./App.tsx",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Legacy aliases (โค้ดเดิมใช้ชื่อเหล่านี้อยู่) ──
        primary: "var(--primary)",
        "primary-hover": "var(--primary-hover)",
        "primary-light": "var(--primary-light)",
        accent: "var(--accent)",
        "neutral-bg": "var(--neutral-bg)",
        "neutral-ink": "var(--neutral-ink)",
        "neutral-muted": "var(--neutral-muted)",
        border: "var(--border)",
        danger: "var(--danger)",
        success: "var(--success)",

        // ── Design-system roles ──
        "on-primary": "var(--on-primary)",
        "primary-container": "var(--primary-container)",
        "on-primary-container": "var(--on-primary-container)",
        secondary: "var(--secondary)",
        "on-secondary": "var(--on-secondary)",
        "secondary-container": "var(--secondary-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        tertiary: "var(--tertiary)",
        "tertiary-container": "var(--tertiary-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",

        surface: "var(--surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "inverse-surface": "var(--inverse-surface)",

        outline: "var(--outline)",
        "outline-variant": "var(--outline-variant)",
        error: "var(--error)",
        "error-container": "var(--error-container)",
        "on-error-container": "var(--on-error-container)",
        "success-container": "var(--success-container)",
        "on-success-container": "var(--on-success-container)",
        "warning-container": "var(--warning-container)",
        "on-warning-container": "var(--on-warning-container)",
        live: "var(--live)",
      },
      borderRadius: {
        '3xl': '1.5rem',
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      maxWidth: {
        content: "1360px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "gutter-mobile": "1rem",
        "gutter-tablet": "1.5rem",
        "gutter-desktop": "2rem",
      },
      fontFamily: {
        prompt: ["Prompt", "sans-serif"],
        display: ["Plus Jakarta Sans", "Prompt", "sans-serif"],
        heading: ["Plus Jakarta Sans", "Prompt", "sans-serif"],
        label: ["Plus Jakarta Sans", "Prompt", "sans-serif"],
        body: ["Be Vietnam Pro", "Prompt", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "display-hero-mobile": ["26px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 4px 24px rgba(15, 23, 42, 0.06)",
        "card-hover": "0 16px 36px rgba(30, 58, 138, 0.12)",
      },
    },
  },
  plugins: [],
}
